[build]
base = "client/"
publish = "client/build/"
command = "npm run build"

[context.rinkeby.environment]
  REACT_APP_HUB_ADDRESS = "0xD216153c06E857cD7f72665E0aF1d7D82172F494"
  REACT_APP_CHAT_APP_ADDRESS = "0x69222CcdA126b22cbC325195B51c7e93b3e16850"
  REACT_APP_NETWORK = "wss://rinkeby.infura.io/ws/v3/cfed977c21914b388137979b1ee79db7"
  REACT_APP_GAS_PRICE = "22000000001"
  REACT_APP_TX_FEE = "81"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
