[build]
base = "client/"
publish = "client/build/"
command = "npm run build"

[context.signUpForm.environment]
  REACT_APP_HUB_ADDRESS = "0x537F27a04470242ff6b2c3ad247A05248d0d27CE"
  REACT_APP_WORKSHOP_POLL_ADDRESS = "0x28b3D5c49584208A11BdECB1c4E68c61c451dFaD"
  REACT_APP_NETWORK = "wss://rinkeby.infura.io/ws/v3/cfed977c21914b388137979b1ee79db7"
  REACT_APP_GAS_PRICE = "22000000001"
  REACT_APP_TX_FEE = "81"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
